<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Restaurantzz homie</title>
  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="Flat-UI-Pro-1.2.5/css/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="Flat-UI-Pro-1.2.5/css/flat-ui.css" rel="stylesheet">
	<link href="css/teststyle.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	<div style="padding-top:30px" class=" navbar navbar-inverse navbar-fixed-top" role="navigation">
	
		<div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	          	<a class="navbar-brand" href="index.php">restaurantzz</a>
        </div>
        
        
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav "><!-- No content -->
          </ul>
          <ul style="display: inline-block; float:right;" class="nav navbar-nav navbar-right">
				<a class="nav-list" style="color:#FFFFFF;" href="about.phtml">about</a>		
				<a class="nav-list" style="color:#FFFFFF;" href="team.phtml">team</a>  
          </ul>
        </div><!--/.nav-collapse -->

</div><!--/.navbar  -->
  	
    <div style="width:75%; margin:auto" class="container">
       <center><br><font size="10">Welcome to Restaurantzz! </font><br><br><font size="6"> Restaurantzz is a web application that takes information from both the Twitter and Yelp API's and maps the most trending restaurants right now nearest to the location you enter. </font></center>
    </div><!-- /.container -->


    <!-- Load JS here for greater good =============================-->
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery-1.8.3.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery.ui.touch-punch.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/bootstrap.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/bootstrap-select.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/bootstrap-switch.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/flatui-checkbox.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/flatui-radio.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/s/jquery.tagsinput.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery.placeholder.js"></script>
  </body>
</html>
