<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Restaurantzz</title>
   	
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="Flat-UI-Pro-1.2.5/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="Flat-UI-Pro-1.2.5/css/flat-ui.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/jquery-ui.min.js"></script>
		<script src="//maps.googleapis.com/maps/api/js?sensor=false&language=en&region=US"></script>
  </head>
  <body>
  	<div id="navigationBar" style="padding-top:30px" class="navbar navbar-inverse navbar-static-top" role="navigation">
		<div class="navbar-header navbar-fixed-top">
          	<a class="navbar-brand" href="index.php">restaurantzz</a>
          	<p class="navbar-text navbar-right"><a class="navbar-link" href="about.phtml">about</a></p>
       		 <p class="navbar-text navbar-right"><a class="navbar-link" href="team.phtml">team</a></p>
        </div>  
	</div><!--/.navbar  -->

	<div id="search" class="container">
		<center>
			<form action="" method= "get" id="createQuery">
				<div class="form-group">
					<span class="twitter-typehead" style="position:realtive; display:inline;">
					<input class="form-control tt-query" type="text" style="position: relative; display:inline; vertical-align: top; background-color: transparent; width: 500px; bottom:1px" id="locationQuery" name ="location" placeholder="Enter A Location"> 
					<input type="hidden" id="latitude" name="lat" />
	  				<input type="hidden" id="longitude" name="long" /> 
	  				<input type="button" value="Search" onclick="getLatLong()" class="btn btn-primary btn-large" style="position: relative; display:inline;" />
				</div>
			</form>
		</center>
	</div><!-- /.container -->
	
 	<div class="mapTemplate" id= "map" style="margin:0 0;width:75%;	height: 600px;border:black; display: inline;float:left"></div>
 	<?php if(count($yelp) != 0){ ?>
 		<script type="text/javascript">
 			directionsDisplay = new google.maps.DirectionsRenderer();
			var latlng=new google.maps.LatLng(<?php echo $lat?>,<?php echo $long ?>);
			var myOptions = {
				zoom:16,
				center: latlng,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			}
			map = new google.maps.Map(document.getElementById('map'), myOptions);

			var geocoder = new google.maps.Geocoder();
			
			
			<?php
				for($i = 0; $i < count($location); $i++)
				{
					echo 'addPinByAddress("' . $location[$i] . '");
					';
				}
			?>
			
			function addPinByAddress(address)
			{
				geocoder.geocode( { 'address': address}, function(results, status) {
			      if (status == google.maps.GeocoderStatus.OK) {
			        map.setCenter(results[0].geometry.location);
			        var marker = new google.maps.Marker({
			            map: map,
			            position: results[0].geometry.location
			        });
			      } else {
			      	if(status.indexOf("OVER_QUERY_LIMIT") == -1)
			      		return;
			        alert("Geocode was not successful for the following reason: " + status);
			      }
			    });
			}
			
			
 		</script>
 	
 	<?php } else {?>
		<script src="task.js"></script>
 	<?php } ?>	
	 <div style="margin:0 0;width:20%; float:right;	height: 600px;border:black; display: inline;">
		<?php foreach($yelp as $index=>$yell){
			echo ($index+1).'. <a href="'.$yell['url'].'">'.$yell['name'].'</a><br>';
		}
		?>
	</div>
	<script type="text/javascript">
		function getLatLong(){
			var address = document.getElementById('locationQuery').value;
			var geo = new google.maps.Geocoder;
  			geo.geocode({'address':address},function(results, status){
     		     if (status == google.maps.GeocoderStatus.OK) {
      		        document.getElementById('latitude').value = results[0].geometry.location['k'];
           		   	document.getElementById('longitude').value = results[0].geometry.location['A'];
              	
           		   	// console.log(results,status);
          		    //console.log('latitude: '+encodeURI(document.getElementById('latitude').value));
         		    //console.log('longitude: '+encodeURI(document.getElementById('longitude').value));
            	
              		// console.log(results[0].geometry.location['k']); //longitude -> don't use this - use the two above
              		// console.log(results[0].geometry.location['A']); //latitude -> don't use this- use the two above
              	
              		document.getElementById("createQuery").submit();
         		 } else {
            		//alert("Geocode was not successful for the following reason: " + status);
            		alert("Ooops, something went wrong. Please input another location.");
             	 }

       		});
  		}
	</script>
	
    <!-- Load JS here for greater good =============================-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery-1.8.3.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery.ui.touch-punch.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/bootstrap.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/bootstrap-select.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/bootstrap-switch.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/flatui-checkbox.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/flatui-radio.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery.tagsinput.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery.placeholder.js"></script>

  </body>
</html>
