<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Restaurantzz homie</title>
   	
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="Flat-UI-Pro-1.2.5/css/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="Flat-UI-Pro-1.2.5/css/flat-ui.css" rel="stylesheet">
	<link href="css/teststyle.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

    <script type="text/javascript">
      /**
       * Called on the intiial page load.
       */
      var map;
      var marker;
      function init() {
        var mapCenter = new google.maps.LatLng(0, 0);
        map = new google.maps.Map(document.getElementById('map_canvas'), {
          zoom: 13,
          mapTypeId: google.maps.MapTypeId.ROADMAP,
          disableDefaultUI: true,
        });

        marker = new google.maps.Marker();
        window.setTimeout(getUsersLocation, 2000);
      }

      function getUsersLocation() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = new google.maps.LatLng(position.coords.latitude,
              position.coords.longitude);
            map.panTo(pos);
            marker.setPosition(pos);
            marker.setMap(map);
          }, function() {
            // Can find the users location
            // Cheat for the talk
            marker.setPosition(new google.maps.LatLng(14.597466, 121.0092));
            marker.setMap(map);
          });
        } else {
          marker.setPosition(new google.maps.LatLng(14.597466, 121.0092));
          marker.setMap(map);
        }
      }

      // Register an event listener to fire when the page finishes loading.
      google.maps.event.addDomListener(window, 'load', init);
    </script>
  </head>
  <body>
  	<div style="padding-top:30px" class=" navbar navbar-inverse navbar-fixed-top" role="navigation">
	
		<div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	          	<a class="navbar-brand" href="index.php">restaurantzz</a>
        </div>
        
        
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav "><!-- No content -->
          </ul>
          <ul style="display: inline-block; float:right;" class="nav navbar-nav navbar-right">
				<a class="nav-list" style="color:#FFFFFF;" href="about.phtml">about</a>		
				<a class="nav-list" style="color:#FFFFFF;" href="team.phtml">team</a> 
				<a class="nav-list" style="color:#FFFFFF;" href="getHashFunc.php">test</a>   
          </ul>
        </div><!--/.nav-collapse -->

</div><!--/.navbar  -->
  	
    <div class="container">
       <center>
	       	<div class="form-group">
		       	<span class="twitter-typehead" style="position:relative; display:inline-block;">
		       		<input class="tt-hint" type="text" autocomplete="off" spellcheck="off"
		       			disabled style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(255, 255, 255);">
		       		<input class="form-control tt-query" type="text" id="typeahead-demo-01" autocomplete="off"
		       			spellcheck="false" dir="auto" style="position: relative; vertical-align: top; background-color: transparent; width: 500px; bottom:17px"placeholder="Enter location to search trending restaurants">
		       		<span style="position: absolute; left: -9999px; visibility: hidden; white-space: nowrap; font-family: Lato, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></span>
		       		<span class="tt-dropdown-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"></span>
		       	</span>
		       	
		       	<a class="btn btn-primary btn-hg" style="postion: relative; vertical-align:top;">Search</a>
	       </div>
       </center>
        <div id="map_canvas"></div>
    </div><!-- /.container -->


    <!-- Load JS here for greater good =============================-->
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery-1.8.3.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery.ui.touch-punch.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/bootstrap.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/bootstrap-select.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/bootstrap-switch.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/flatui-checkbox.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/flatui-radio.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/s/jquery.tagsinput.js"></script>
    <script src="Flat-UI-Pro-1.2.5/css/js/jquery.placeholder.js"></script>
  </body>
</html>
