<!DOCTYPE html>
<html>
  <head>
    <title>Place Autocomplete</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    
    <!-- Loading Bootstrap -->
    <link href="Flat-UI-Pro-1.2.5/css/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="Flat-UI-Pro-1.2.5/css/flat-ui.css" rel="stylesheet">
    
    <!-- Individual CSS -->
    <link href="css/index.css" rel="stylesheet">
    
    <!-- Google Maps Scripts -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
	<script src="map.js"></script>
	
  </head>
  <body>
  	
    <input id="pac-input" class="controls" type="text"
        placeholder="Enter a location">
    <div id="map"></div>
   

 
<script type="text/javascript"> 
jQuery(document).ready(function() {
 
	 Load google map
	var map = new google.maps.Map( document.getElementById("gmap"),  {
		center: new google.maps.LatLng(0,0),
		zoom: 3,
		mapTypeId: google.maps.MapTypeId.ROADMAP,
		panControl: false,
		streetViewControl: false,
		mapTypeControl: false
	});
 
 
	//jQuery('input[name=search]').click(function() {
 
		var geocoder = new google.maps.Geocoder(); 
		geocoder.geocode({
				address : jQuery('results[name=address]').val(), 
				region: 'no' 
			},
		    function(results, status) {
		    	if (status.toLowerCase() == 'ok') {
					// Get center
					var coords = new google.maps.LatLng(
						results[0]['address'].lat(),
						results[0]['address'].lng()
					);
					jQuery('#coords').html('Latitute: ' + coords.lat() + '    Longitude: ' + coords.lng() );
 consol.log(coords);
					map.setCenter(coords);
					map.setZoom(18);
 
					// Set marker also
					marker = new google.maps.Marker({
						position: coords, 
						map: map, 
						title: jQuery('input[name=address]').val(),
					});
 
		    	}
			}
		);
	});
 
});
 </script>
  </body>
</html>