<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Restaurantzz homie</title>
   	
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="Flat-UI-Pro-1.2.5/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="Flat-UI-Pro-1.2.5/css/flat-ui.css" rel="stylesheet">
	<link href="css/teststyle.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	<div style="padding-top:30px" class=" navbar navbar-inverse navbar-fixed-top" role="navigation">
	
		<div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	          	<a class="navbar-brand" href="index.php">restaurantzz</a>
        </div>
        
        
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav "><!-- No content -->
          </ul>
          <ul style="display: inline-block; float:right;" class="nav navbar-nav navbar-right">
				<<a class="nav-list" style="color:#FFFFFF;" href="about.phtml">about</a>		
				<a class="nav-list" style="color:#FFFFFF;" href="team.phtml">team</a>  
          </ul>
        </div><!--/.nav-collapse -->

</div><!--/.navbar  -->
  	
   <div class="container">
    <!--	<div class="row">
    		 
    <div class="span 12"><font size="10">  This web application was made at Hack UCI by:</font>  </div> </div>
   	<div class="row">
      <div class="span 3"> <img src="images/grace-pai.jpg" alt="Grace Pai" height="80" width="80"></div> 
      <div class="span 9">	<font size="5">Grace Pai is an informatics major at UC Irvine and is graduating in 2014. </font> </div></div> 
      <div class="row">
        <div class="span 3"><img src="images/stevenrutherford.JPG" alt="Steven Rutherford"height="80" width="80"></div>
        	<div class="span 9"><font size="5"> Steven Rutherford is a computer engineering major at UC Irvine and is graduating in 2014.</font> </div></div> 
      <div class="span 3"> <img src="images/rachelweiner.jpg" alt="Rachel Weiner" height="80" width="80"></div>
       <div class="span 9"><font size = "5">Rachel Weiner is a computer science and informatics double major at UC Irvine and will be graduating in 2016. </font></div></div> 
    <center> <div class="span 3"><img src="images/pengwang.JPG" alt="Peng Wang" height="80" width="80"></div>
     <div class="span 9"><font size ="5">Peng Wang is a computer science major at UC Riverside and will be graduating in 2015. </font></div> </div>
    </center> 
     </center>
    -->
    
     	
    
    	
    		<br><br><br> 
  <font size="10">  This web application was made at Hack UCI by:</font>  
  
  
      <br><br><img src="images/grace-pai.jpg" alt="Grace Pai" height="80" width="80"> 
     <font size="5">Grace Pai is an informatics major at UC Irvine and is graduating in 2014. </font>
     
    <br><br>   <img src="images/stevenrutherford.JPG" alt="Steven Rutherford"height="80" width="80">
        	<font size="5"> Steven Rutherford is a computer engineering major at UC Irvine and is graduating in 2014.</font>
    <br><br><img src="images/rachelweiner.jpg" alt="Rachel Weiner" height="80" width="80">
      <font size = "5">Rachel Weiner is a cs and informatics double major at UC Irvine and will be graduating in 2016. </font>
  <br><br><img src="images/pengwang.JPG" alt="Peng Wang" height="80" width="80">
    <font size ="5">Peng Wang is a computer science major at UC Riverside and will be graduating in 2015. </font>
    
    
  


    </div><!-- /.container -->


    <!-- Load JS here for greater good =============================-->
    <script src="Flat-UI-Pro-1.2.5/js/jquery-1.8.3.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery.ui.touch-punch.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/bootstrap.min.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/bootstrap-select.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/bootstrap-switch.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/flatui-checkbox.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/flatui-radio.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery.tagsinput.js"></script>
    <script src="Flat-UI-Pro-1.2.5/js/jquery.placeholder.js"></script>
  </body>
</html>
